version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/server
    entrypoint: >
      sh -c "
             dos2unix /server/**/*  &&
             /server/backend/startup.sh
      "
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    links:
      - backend
    entrypoint: >
      sh -c "
             dos2unix /frontend/**/*  &&
             /frontend/startup.sh
      " 
