version: "3.9"
services:
  backend:
    image: "nikolaik/python-nodejs"
    ports:
      - "8000:8000"
    volumes:
      - .:/server
    entrypoint: sh -c "/server/backend/startup.sh"
  frontend:
    image: "nikolaik/python-nodejs"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    links:
      - backend