# Generated by Django 4.0.6 on 2022-07-21 21:20

import random

from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0001_initial"),
        ("base_user", "0002_alter_baseuser_phone_number"),
    ]

    def generate_data(apps, schema_editor):
        from researcher.models import Researcher

        with transaction.atomic():
            Researcher.create(
                email="mta.researchmate@gmail.com",
                username="gal",
                password="123456",
                first_name="Gal",
                last_name="Lior",
                phone_number=str(random.randint(1000000000, 9999999999)),
            )

    operations = [
        migrations.RunPython(generate_data),
    ]
