# Generated by Django 4.0.6 on 2022-07-21 20:48

import random
import names
from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ("participant", "0001_initial"),
        ("base_user", "0002_alter_baseuser_phone_number"),
    ]

    def generate_data(apps, schema_editor):
        from participant.models import Participant

        with transaction.atomic():
            for i in range(1, 100):
                gender = "female"
                if bool(random.getrandbits(1)):
                    gender = "male"
                first_name = names.get_first_name(gender=gender)
                last_name = names.get_last_name()
                Participant.create(
                    email="{}.{}@gmail.com".format(first_name, last_name),
                    username="{}.{}".format(first_name, last_name),
                    password="123456",
                    first_name=first_name,
                    last_name=last_name,
                    phone_number="05" + str(random.randint(0, 5)) + str(random.randint(1000000, 9999999)),
                )
            Participant.create(
                email="party@gmail.com",
                username="party",
                password="123456",
                first_name="Party",
                last_name="Participant",
                phone_number="05" + str(random.randint(0, 5)) + str(random.randint(1000000, 9999999)),
            )

    operations = [
        migrations.RunPython(generate_data),
    ]
