name: PyTest
on: pull_request
jobs:
  pytest:
    name: PyTest
    runs-on: ubuntu-20.04
    container: nikolaik/python-nodejs:python3.10-nodejs19
    steps:
#      - name: Install Pipenv and git
#        run: dnf install -y pipenv git
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: pipenv sync --dev
      - name: Run PyTest
        run: pipenv run pytest -v backend/
